inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisabledByDefault: true
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'spec/dummy/**/*'
   - 'gemfiles/*'
require:
  - rubocop-rails
  - rubocop-rspec
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'
Metrics/BlockLength:
  Exclude:
    - 'config/environments/production.rb'
    - '**/*_spec.rb'
    - 'spec/support/shared_examples/**'
    - '**/factories/**/*'
    - 'vendor/**/*'
Layout/LineLength:
  Max: 180
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'
Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/support/shared_examples/**'
Lint/Debugger:
  Enabled: false
Layout/DefEndAlignment:
  AutoCorrect: true
Layout/EndAlignment:
  AutoCorrect: true
Lint/AmbiguousBlockAssociation:
  Exclude:
   - '**/*_spec.rb'
   - 'spec/support/shared_examples/**'
Lint/NonDeterministicRequireOrder:
  Enabled: false
Rails:
  Enabled: true
Rails/ActiveRecordAliases:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/Output:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
Security/Open:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/DateTime:
  Enabled: false
Style/Documentation:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
