inherit_from:
  - .rubocop_rails.yml
  - .rubocop_rspec.yml
  - .rubocop_strict.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard/cop/semantic_blocks
  - ./lib/rubocop/rspec/let_bang

inherit_gem:
  standard: config/base.yml

AllCops:
  DisplayCopNames: true
  DisabledByDefault: true
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'spec/dummy/**/*'
   - 'gemfiles/*'
   - 'lib/generators/**/*'

RSpec/LetBang:
  Enabled: true
